[package]
name = "n-body"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.3", features = ["wayland"] }
bevy_egui = {version = "0.33", features = ["bevy_picking"]}
egui_plot = "0.31.0"
rand = "0.9.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
